eureka:
  client:
    serviceUrl:
      defaultZone: http://172.30.32.1:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: account-service
  boot:
    admin:
      client:
        url: http://172.30.32.1:8080/
